export const JAVASCRIPT_TYPES = {
  ARRAY: 'array',
  BOOLEAN: 'boolean',
  BUFFER: 'buffer',
  DATE: 'date',
  ERROR: 'error',
  FUNCTION: 'function',
  GENERATOR: 'generator',
  GENERATORFUNCTION: 'generatorfunction',
  HYBRID: 'hybrid',
  MAP: 'map',
  NULL: 'null',
  NUMBER: 'number',
  OBJECT: 'object',
  PROMISE: 'promise',
  REGEXP: 'regexp',
  SET: 'set',
  STREAM: 'stream',
  STRING: 'string',
  SYMBOL: 'symbol',
  UNDEFINED: 'undefined',
  WEAKMAP: 'weakmap',
  WEAKSET: 'weakset',
} as const

export type JavascriptType = typeof JAVASCRIPT_TYPES[keyof typeof JAVASCRIPT_TYPES]
